### PR TITLE
Add iflightf411rx/zeus 5 fr /zeus 10 targets support

### PR DESCRIPTION
**Pull request by hallucino**
Tested on the baby nazgul.

Hope it is ok, I attached the dump from BF for double checking please :)

[BTFL_cli_Baby_Nazgul_20210909_074926.txt](https://github.com/NotFastEnuf/NFE_QUICKSILVER/files/7134745/BTFL_cli_Baby_Nazgul_20210909_074926.txt)

### CODE REVIEW

**Comment by hallucino** [comment]
Is it ok ?

**Comment by bkleiner** [comment]
Do you have a link to this board somewhere? i can't find any reference to it.
Looks to me like its really just another `matekf411rx` clone

**Comment by hallucino** [comment]
Here it is:
https://shop.iflight-rc.com/iFlight-1S-Baby-Nazgul-Nano-FPV-Drone-pro15

Here a dump if the 73 version:
[BTFL_cli_Baby_Nazgul 73_20211026_145412.txt](https://github.com/NotFastEnuf/NFE_QUICKSILVER/files/7512761/BTFL_cli_Baby_Nazgul.73_20211026_145412.txt)
80

**Comment by hallucino** [comment]
Added target for the new HGLRC zeus boards:
https://www.hglrc.com/collections/aio/products/hglrc-zeus5-fr-aio-1-2s-f411-flight-controller-5a-bl_s-4in1-esc-frsky-spi-rx
https://www.hglrc.com/collections/new-arrivals/products/hglrc-zeus10-aio-fpv-racing-drone-2-6s-f411-flight-controller-10a-bl_s-4in1-esc

[BTFL_cli_KT20_20211109_214327.txt](https://github.com/NotFastEnuf/NFE_QUICKSILVER/files/7512767/BTFL_cli_KT20_20211109_214327.txt
[BTFL_cli_Petrel_65mm_20211102_164457.txt](https://github.com/NotFastEnuf/NFE_QUICKSILVER/files/7512769/BTFL_cli_Petrel_65mm_20211102_164457.txt)
)

**Comment by bkleiner** [comment]
hold up, couple of things:
1. please submit one pull request per board.
2. please submit them here https://github.com/BossHobby/QUICKSILVER
3. please ensure these boards are actually distinct and not the same target with different names.
4. the cli dumps dont make for great reference because its unclear what was changed, please provide links to the corresponding [unified target](https://github.com/betaflight/unified-targets) 

once we got all that sorted i will be more then happy to merge all of them in the [main repo](https://github.com/BossHobby/QUICKSILVER) and add them to the build pipeline so the hexes get released

**Comment by hallucino** [comment]
yes ok make sense, let me dot that ! Oh so the other repository is more active ?? Excellent !!!

**Pull request closed without merging**
